### PR TITLE
Issue148 - `0` children regression in dash==0.40.0

### LINKED ISSUE #148: Regression going from Dash 0.39 to 0.40 -- implicit `0` child is missing from app
Note the difference in the last table.

Code
```
import dash
import dash_core_components as dcc
import dash_html_components as html
import pandas as pd

df = pd.read_csv(
    'https://gist.githubusercontent.com/chriddyp/'
    'c78bf172206ce24f77d6363a2d754b59/raw/'
    'c353e8ef842413cae56ae3920b8fd78468aa4cb2/'
    'usa-agricultural-exports-2011.csv')


def generate_table(dataframe, max_rows=10):
    return html.Div([
        html.Table(
            # Header
            [html.Tr([html.Th(col) for col in dataframe.columns])] +

            # Body
            [html.Tr([
                html.Td(children=[dataframe.iloc[i][col]]) for col in dataframe.columns
            ]) for i in range(min(len(dataframe), max_rows))]
        ),
        html.Table(
            # Header
            [html.Tr([html.Th(col) for col in dataframe.columns])] +

            # Body
            [html.Tr([
                html.Td([dataframe.iloc[i][col]]) for col in dataframe.columns
            ]) for i in range(min(len(dataframe), max_rows))]
        ),
        html.Table(
            # Header
            [html.Tr([html.Th(col) for col in dataframe.columns])] +

            # Body
            [html.Tr([
                html.Td(dataframe.iloc[i][col]) for col in dataframe.columns
            ]) for i in range(min(len(dataframe), max_rows))]
        )
    ])

external_stylesheets = ['https://codepen.io/chriddyp/pen/bWLwgP.css']

app = dash.Dash(__name__, external_stylesheets=external_stylesheets)

app.layout = html.Div(children=[
    html.H4(children='US Agriculture Exports (2011)'),
    generate_table(df, 5)
])

if __name__ == "__main__":
    app.run_server(port=8070)
```

Dash 0.39
image

Dash 0.40
image

### PR DESCRIPTION
**Pull request by Marc-Andre-Rivet**
FIxes #148.

Found the issue in dash-docs percy deltas in https://percy.io/plotly/dash-docs/builds/1719186
image

Add test for array case `children=[0]`, this passes with the existing code: https://github.com/plotly/dash-renderer/commit/0602a155e12ba718b1a9bc764b93e32c6bd78004

Add test for non-array case `children=0`, this fails with the existing code: https://github.com/plotly/dash-renderer/commit/d48e81dd2f52434a7fb86a707a8483e26e779078

Fix: https://github.com/plotly/dash-renderer/commit/b600b8cd296dd0ade14737dc6985e4596b10e736

### CODE REVIEW

File: src/TreeContainer.js [hunk 1]
```diff
@@ -33,7 +33,7 @@ const createContainer = component => isSimpleComponent(component) ?
 
 class TreeContainer extends Component {
     getChildren(components) {
-        if (!components) {
+        if (isNil(components)) {
```
Comment (Marc-Andre-Rivet) [inline src/TreeContainer.js]: 0 is falsy..

File: tests/test_render.py [hunk 2]
```diff
@@ -475,6 +475,32 @@ def test_initial_state(self):
 
         assert_clean_console(self)
 
+    def test_array_of_nully_child(self):
+        app = Dash(__name__)
+        app.layout = html.Div(id='nully-wrapper', children=[0])
```
Comment (Marc-Andre-Rivet) [inline tests/test_render.py]: This worked and needs to keep working

File: tests/test_render.py [hunk 3]
```diff
@@ -475,6 +475,32 @@ def test_initial_state(self):
...
+        self.wait_for_element_by_css_selector('#nully-wrapper')
+        wrapper = self.driver.find_element_by_id('nully-wrapper')
+
+        self.assertEqual(wrapper.get_attribute('innerHTML'), '0')
+
+        assert_clean_console(self)
+
+    def test_of_nully_child(self):
+        app = Dash(__name__)
+        app.layout = html.Div(id='nully-wrapper', children=0)
```
Comment (Marc-Andre-Rivet) [inline tests/test_render.py]: This is the regression case

File: tests/test_render.py [hunk 4]
```diff
@@ -104,7 +104,7 @@ def request_queue_assertions(
 
         if expected_length is not None:
             self.assertEqual(len(request_queue), expected_length)
-
```
Comment (alexcjohnson) [inline tests/test_render.py]: Oh noes, trailing whitespace courtesy of @chriddyp ??? 😅

Comment (chriddyp) [reply tests/test_render.py]: no way!! 🙊 🙊 🙊

File: tests/test_render.py (hunk 2 above)
Comment (alexcjohnson) [reply tests/test_render.py]: nice. I'd call this falsy though, not nully.

File: tests/test_render.py [hunk 5]
```diff
@@ -475,6 +475,32 @@ def test_initial_state(self):
...
+    def test_array_of_nully_child(self):
+        app = Dash(__name__)
+        app.layout = html.Div(id='nully-wrapper', children=[0])
+
+        self.startServer(app)
+
+        self.wait_for_element_by_css_selector('#nully-wrapper')
+        wrapper = self.driver.find_element_by_id('nully-wrapper')
+
+        self.assertEqual(wrapper.get_attribute('innerHTML'), '0')
```
Comment (alexcjohnson) [inline tests/test_render.py]: Can't this whole section just be [`self.wait_for_text_to_equal('#nully-wrapper', '0')`](https://github.com/plotly/dash-renderer/blob/master/tests/test_render.py#L59)?

File: tests/test_render.py (hunk 2 above)
Comment (Marc-Andre-Rivet) [reply tests/test_render.py]: good point

File: tests/test_render.py (hunk 5 above)
Comment (Marc-Andre-Rivet) [reply tests/test_render.py]: Hum.. wasn't aware of that one. Looks like `wait_for_text_to_equal` uses `value` and that would mean it's only meant to be used with `<input />` elements.

Comment (chriddyp) [reply tests/test_render.py]: `value` _or_ `.text`:
https://github.com/plotly/dash-renderer/blob/2c0169c52f5d604db48285814836fe394a0aea07/tests/test_render.py#L63

Comment (Marc-Andre-Rivet) [reply tests/test_render.py]: I can't read code it seems. Will update to use suggested.

File: tests/test_render.py (hunk 3 above)
Comment (byronz) [reply tests/test_render.py]: too late for the comment, but this should be merged with the `test_initial_state`.
